// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Inventory.Shared.Models;

[Table("Store")]
public partial class Store
{
    [Key]
    public int StoreId { get; set; }

    [StringLength(255)]
    public string Name { get; set; } = null!;

    [StringLength(255)]
    public string Location { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? DateOpened { get; set; }

    [ForeignKey("StoreId")]
    [InverseProperty("Stores")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    public String Slug => Name.Replace(" ", "-").ToLower();
}